### ISSUE TITLE
Update Puppeteer (or replace with Playwright)

### ISSUE THREAD

**Issue by ChristianMurphy** [remcohaszing/remark-mermaidjs#2]
Currently puppeteer is tested with version 11
https://github.com/remcohaszing/remark-mermaidjs/blob/9c664676214441ef231e53e565b2e8ce413d8aac/package.json#L69
Puppeteer is now on the 13.x release line https://github.com/puppeteer/puppeteer/releases/tag/v13.0.0

It would be good to test with latest, or alternatively migrate to playwright, which is built by the original puppeteer team, and adds new features https://github.com/microsoft/playwright

**Comment by remcohaszing** [comment]
Puppeteer frequently creates major releases with small breaking updates that don’t affect remark-mermaidjs. This is why I now accept a `>=` peer dependency range and the dev dependency is outdated. I currently use it with the latest version of puppeteer at work.

I think playwright downloads even more than one browser, so that might be a heavier dependency? I could be wrong though. Having support for multiple renderers as stated in #3 sounds great regardless. I imagine pulling in puppeteer in a project using playwright or playwright in a project already using puppeteer is both equally annoying.

**Comment by ChristianMurphy** [comment]
> Puppeteer frequently creates major releases with small breaking updates that don’t affect remark-mermaidjs. This is why I now accept a >= peer dependency range and the dev dependency is outdated. I currently use it with the latest version of puppeteer at work.

Good to know that does/should work.
I wonder if there would be a way to test across puppeteer versions with CI, similar to how CI can try a matrix of Node versions and operating systems. :thinking: 

> I think playwright downloads even more than one browser

It does, I believe it by default installs a copy of Chromium, Webkit, and Firefox.
There may be a way to limit those downloads.

> I imagine pulling in puppeteer in a project using playwright or playwright in a project already using puppeteer is both equally annoying.

Agreed.
A possible future could be something like https://github.com/remarkjs/remark-math
Where different rendering engines different packages which act as drop in replacements for each other.

**Comment by remcohaszing** [comment]
> > Puppeteer frequently creates major releases with small breaking updates that don’t affect remark-mermaidjs. This is why I now accept a >= peer dependency range and the dev dependency is outdated. I currently use it with the latest version of puppeteer at work.
> 
> Good to know that does/should work. I wonder if there would be a way to test across puppeteer versions with CI, similar to how CI can try a matrix of Node versions and operating systems. :thinking:

It’s possible to run `npm install $PUPPETEER_VERSION` based on a matrix of various puppeteer versions. Still adding a version to the matrix for every puppeteer release would just be a maintenance burden.

> > I imagine pulling in puppeteer in a project using playwright or playwright in a project already using puppeteer is both equally annoying.
> 
> Agreed. A possible future could be something like https://github.com/remarkjs/remark-math Where different rendering engines different packages which act as drop in replacements for each other.

I was thinking an export map can used for differentiate between browser and node builds.

The node API could look like this, where each renderer dynamically imports the (heavy) rendering dependency:

```ts
import remark from 'remark'
import remarkMermaid { jsdomRenderer, playwrightRenderer, puppeteerRenderer } from 'remark-mermaidjs'

remark()
  .use(remarkMermaid, { renderer: jsdomRenderer }) // Doesn’t work, but wishful thinking 🤞
  // Or…
  .use(remarkMermaid, { renderer: playwrightRenderer })
  // Or…
  .use(remarkMermaid, { renderer: puppeteerRenderer }) // Keep this as default?
```

The browser API could look like below. It doesn’t need a specific renderer, because it can just import and invoke mermaid in the browser directly.

```ts
import remark from 'remark'
import remarkMermaid from 'remark-mermaidjs'

remark()
  .use(remarkMermaid)
```

**Comment by remcohaszing** [comment]
I have replaced `puppeteer` with `puppeteer-core`. This strips the heavy part of puppeteer (downloading Chrome). I wouldn’t mind migrating to playwright eventually, but for now I’m ok with using puppeteer.
