### ISSUE TITLE
mermaid flowchart looks like broken

### ISSUE THREAD

**Issue by KimPinot** [remcohaszing/remark-mermaidjs#6]
Hello. I'm happy to use your project.

However, My mermaid app looks like broken at When I using Korean content. (second flowchart)
Also, It looks like short height because my content sliced on svg.

<img width="755" alt="스크린샷 2022-09-09 18 14 00" src="https://user-images.githubusercontent.com/42037851/189315782-42f10317-ad6d-420f-8074-510cb528b097.png">

How can I fix this issue? or any clue?

Here is some helpful link.

[article](https://nabi.kim/notes/mermaid/test) [markdown](https://github.com/KimPinot/new-blog/blob/main/notes/mermaid/test.md) [unifiedjs](https://github.com/KimPinot/new-blog/blob/f56468c8f008793018f01d515b064cc85c6fe0bd/modules/post/article.ts#L51-L83)

**Comment by remcohaszing** [comment]
Thanks for reporting this! There are some things you can do to help:

- Which version are you using? I recently released version 3.0.0. Does this issue exist when changing to version 2.1.1? Or if you’re using that, does upgrading to 3.0.0 fix it?
- Does the issue go away if you disable minification? (Use the option `svgo: null`)
- Could you send a pull request which adds a [test fixture](https://github.com/remcohaszing/remark-mermaidjs/tree/main/__fixtures__)?

**Comment by KimPinot** [comment]
* Which version are you using? =>  I'm using 3.0.0 version.
* When I disable svgo, image sliced issue was fixed, but Korean broken issue not resolved :(
* Just a second!

**Comment by KimPinot** [comment]
By the way, I think It's also bug.
Below image, Requriment's base line was sliced.

<img width="146" alt="스크린샷 2022-09-09 21 32 25" src="https://user-images.githubusercontent.com/42037851/189350553-bb37fac5-e6be-4daf-b1eb-35e9f5beeed3.png">

**Comment by remcohaszing** [comment]
It turns out you need to install these fonts.

Mermaid uses the actual DOM element sizes for calculation. These are different for different fonts. This is even more apparent for characters that aren’t available in the font that’s used, such as CJK in many situations.

For example, the artifact in [this action run](https://github.com/remcohaszing/remark-mermaidjs/actions/runs/3328732033) shows how the page is rendered before the DOM is extracted.

[This action run](https://github.com/remcohaszing/remark-mermaidjs/actions/runs/3328852372) did the same, but first the fonts were installed using `playwright install --with-deps`.
